import { Player, PlayerStat, Injury, TrainingSession } from "@/lib/types";

const POSITIONS = ["Forward", "Midfielder", "Defender", "Goalkeeper"];
const TEAMS = [
  "Manchester United",
  "Barcelona",
  "Real Madrid",
  "Bayern Munich",
  "Paris Saint-Germain",
  "Liverpool",
  "Chelsea",
  "Juventus",
  "AC Milan",
  "Inter Milan",
];
const NATIONALITIES = [
  "England",
  "Spain",
  "France",
  "Germany",
  "Brazil",
  "Argentina",
  "Portugal",
  "Italy",
  "Netherlands",
  "Belgium",
];

export const MOCK_PLAYERS: Player[] = [
  {
    id: "1",
    name: "Marcus Silva",
    age: 24,
    dateOfBirth: new Date("1999-05-15"),
    position: "Forward",
    currentTeam: "Manchester United",
    nationality: "Brazil",
    height: 182,
    weight: 78,
    status: "contracted",
    overallRating: 87,
    imageUrl: "https://ui-avatars.com/api/?name=Marcus+Silva&background=random",
    createdAt: new Date("2023-01-15"),
    updatedBy: "admin1",
  },
  {
    id: "2",
    name: "James Rodriguez",
    age: 26,
    dateOfBirth: new Date("1997-08-22"),
    position: "Midfielder",
    currentTeam: "Barcelona",
    nationality: "Spain",
    height: 175,
    weight: 72,
    status: "available",
    overallRating: 84,
    imageUrl: "https://ui-avatars.com/api/?name=James+Rodriguez&background=random",
    createdAt: new Date("2023-02-10"),
    updatedBy: "scout1",
  },
  {
    id: "3",
    name: "Thomas Müller",
    age: 28,
    dateOfBirth: new Date("1995-11-30"),
    position: "Defender",
    currentTeam: "Bayern Munich",
    nationality: "Germany",
    height: 188,
    weight: 85,
    status: "contracted",
    overallRating: 85,
    imageUrl: "https://ui-avatars.com/api/?name=Thomas+Muller&background=random",
    createdAt: new Date("2023-01-20"),
    updatedBy: "admin1",
  },
  {
    id: "4",
    name: "Antoine Dubois",
    age: 23,
    dateOfBirth: new Date("2000-03-12"),
    position: "Forward",
    currentTeam: "Paris Saint-Germain",
    nationality: "France",
    height: 179,
    weight: 75,
    status: "contracted",
    overallRating: 89,
    imageUrl: "https://ui-avatars.com/api/?name=Antoine+Dubois&background=random",
    createdAt: new Date("2023-03-05"),
    updatedBy: "scout2",
  },
  {
    id: "5",
    name: "David Foster",
    age: 30,
    dateOfBirth: new Date("1993-07-18"),
    position: "Goalkeeper",
    currentTeam: "Liverpool",
    nationality: "England",
    height: 192,
    weight: 88,
    status: "contracted",
    overallRating: 86,
    imageUrl: "https://ui-avatars.com/api/?name=David+Foster&background=random",
    createdAt: new Date("2023-01-08"),
    updatedBy: "admin1",
  },
  {
    id: "6",
    name: "Carlos Mendes",
    age: 21,
    dateOfBirth: new Date("2002-09-25"),
    position: "Midfielder",
    currentTeam: "Real Madrid",
    nationality: "Portugal",
    height: 177,
    weight: 71,
    status: "available",
    overallRating: 82,
    imageUrl: "https://ui-avatars.com/api/?name=Carlos+Mendes&background=random",
    createdAt: new Date("2023-04-12"),
    updatedBy: "scout1",
  },
  {
    id: "7",
    name: "Leonardo Rossi",
    age: 27,
    dateOfBirth: new Date("1996-12-08"),
    position: "Defender",
    currentTeam: "Juventus",
    nationality: "Italy",
    height: 185,
    weight: 82,
    status: "contracted",
    overallRating: 83,
    imageUrl: "https://ui-avatars.com/api/?name=Leonardo+Rossi&background=random",
    createdAt: new Date("2023-02-20"),
    updatedBy: "scout2",
  },
  {
    id: "8",
    name: "Juan Martinez",
    age: 25,
    dateOfBirth: new Date("1998-04-16"),
    position: "Forward",
    currentTeam: "Barcelona",
    nationality: "Argentina",
    height: 180,
    weight: 76,
    status: "injured",
    overallRating: 88,
    imageUrl: "https://ui-avatars.com/api/?name=Juan+Martinez&background=random",
    createdAt: new Date("2023-01-30"),
    updatedBy: "admin1",
  },
  {
    id: "9",
    name: "Kevin De Bruyne Jr",
    age: 22,
    dateOfBirth: new Date("2001-06-20"),
    position: "Midfielder",
    currentTeam: "Chelsea",
    nationality: "Belgium",
    height: 181,
    weight: 74,
    status: "available",
    overallRating: 85,
    imageUrl: "https://ui-avatars.com/api/?name=Kevin+DeBruyne&background=random",
    createdAt: new Date("2023-03-15"),
    updatedBy: "scout1",
  },
  {
    id: "10",
    name: "Rafael Santos",
    age: 29,
    dateOfBirth: new Date("1994-10-05"),
    position: "Defender",
    currentTeam: "AC Milan",
    nationality: "Brazil",
    height: 186,
    weight: 83,
    status: "contracted",
    overallRating: 84,
    imageUrl: "https://ui-avatars.com/api/?name=Rafael+Santos&background=random",
    createdAt: new Date("2023-02-28"),
    updatedBy: "scout2",
  },
  {
    id: "11",
    name: "Olivier Giroud",
    age: 31,
    dateOfBirth: new Date("1992-11-22"),
    position: "Forward",
    currentTeam: "Inter Milan",
    nationality: "France",
    height: 193,
    weight: 90,
    status: "contracted",
    overallRating: 81,
    imageUrl: "https://ui-avatars.com/api/?name=Olivier+Giroud&background=random",
    createdAt: new Date("2023-01-12"),
    updatedBy: "admin1",
  },
  {
    id: "12",
    name: "Sergio Ramos Jr",
    age: 26,
    dateOfBirth: new Date("1997-03-30"),
    position: "Defender",
    currentTeam: "Real Madrid",
    nationality: "Spain",
    height: 184,
    weight: 81,
    status: "available",
    overallRating: 86,
    imageUrl: "https://ui-avatars.com/api/?name=Sergio+Ramos&background=random",
    createdAt: new Date("2023-02-05"),
    updatedBy: "scout1",
  },
  {
    id: "13",
    name: "Manuel Neuer II",
    age: 24,
    dateOfBirth: new Date("1999-07-14"),
    position: "Goalkeeper",
    currentTeam: "Bayern Munich",
    nationality: "Germany",
    height: 193,
    weight: 92,
    status: "contracted",
    overallRating: 87,
    imageUrl: "https://ui-avatars.com/api/?name=Manuel+Neuer&background=random",
    createdAt: new Date("2023-01-25"),
    updatedBy: "admin1",
  },
  {
    id: "14",
    name: "Harry Kane II",
    age: 27,
    dateOfBirth: new Date("1996-08-28"),
    position: "Forward",
    currentTeam: "Manchester United",
    nationality: "England",
    height: 188,
    weight: 86,
    status: "contracted",
    overallRating: 90,
    imageUrl: "https://ui-avatars.com/api/?name=Harry+Kane&background=random",
    createdAt: new Date("2023-03-01"),
    updatedBy: "scout2",
  },
  {
    id: "15",
    name: "Virgil van Dijk Jr",
    age: 28,
    dateOfBirth: new Date("1995-12-08"),
    position: "Defender",
    currentTeam: "Liverpool",
    nationality: "Netherlands",
    height: 193,
    weight: 92,
    status: "contracted",
    overallRating: 89,
    imageUrl: "https://ui-avatars.com/api/?name=Virgil+VanDijk&background=random",
    createdAt: new Date("2023-02-14"),
    updatedBy: "admin1",
  },
  {
    id: "16",
    name: "Luka Modric II",
    age: 25,
    dateOfBirth: new Date("1998-09-09"),
    position: "Midfielder",
    currentTeam: "Real Madrid",
    nationality: "Spain",
    height: 172,
    weight: 66,
    status: "available",
    overallRating: 88,
    imageUrl: "https://ui-avatars.com/api/?name=Luka+Modric&background=random",
    createdAt: new Date("2023-03-20"),
    updatedBy: "scout1",
  },
  {
    id: "17",
    name: "Paulo Dybala Jr",
    age: 26,
    dateOfBirth: new Date("1997-11-15"),
    position: "Forward",
    currentTeam: "Juventus",
    nationality: "Argentina",
    height: 177,
    weight: 75,
    status: "contracted",
    overallRating: 85,
    imageUrl: "https://ui-avatars.com/api/?name=Paulo+Dybala&background=random",
    createdAt: new Date("2023-01-18"),
    updatedBy: "scout2",
  },
  {
    id: "18",
    name: "Thibaut Courtois Jr",
    age: 29,
    dateOfBirth: new Date("1994-05-11"),
    position: "Goalkeeper",
    currentTeam: "Chelsea",
    nationality: "Belgium",
    height: 199,
    weight: 96,
    status: "contracted",
    overallRating: 88,
    imageUrl: "https://ui-avatars.com/api/?name=Thibaut+Courtois&background=random",
    createdAt: new Date("2023-02-22"),
    updatedBy: "admin1",
  },
  {
    id: "19",
    name: "Neymar Jr II",
    age: 23,
    dateOfBirth: new Date("2000-02-05"),
    position: "Forward",
    currentTeam: "Paris Saint-Germain",
    nationality: "Brazil",
    height: 175,
    weight: 68,
    status: "available",
    overallRating: 91,
    imageUrl: "https://ui-avatars.com/api/?name=Neymar+Jr&background=random",
    createdAt: new Date("2023-03-10"),
    updatedBy: "scout1",
  },
  {
    id: "20",
    name: "Marco Verratti Jr",
    age: 27,
    dateOfBirth: new Date("1996-11-05"),
    position: "Midfielder",
    currentTeam: "Paris Saint-Germain",
    nationality: "Italy",
    height: 165,
    weight: 60,
    status: "contracted",
    overallRating: 84,
    imageUrl: "https://ui-avatars.com/api/?name=Marco+Verratti&background=random",
    createdAt: new Date("2023-01-28"),
    updatedBy: "scout2",
  },
];

export const MOCK_STATS: PlayerStat[] = [
  {
    id: "s1",
    playerId: "1",
    matchDate: new Date("2024-10-15"),
    opponent: "Liverpool",
    goals: 2,
    assists: 1,
    minutesPlayed: 90,
    rating: 8.5,
    seasonId: "2024",
  },
  {
    id: "s2",
    playerId: "1",
    matchDate: new Date("2024-10-08"),
    opponent: "Chelsea",
    goals: 1,
    assists: 0,
    minutesPlayed: 85,
    rating: 7.8,
    seasonId: "2024",
  },
  {
    id: "s3",
    playerId: "4",
    matchDate: new Date("2024-10-14"),
    opponent: "Lyon",
    goals: 3,
    assists: 2,
    minutesPlayed: 90,
    rating: 9.2,
    seasonId: "2024",
  },
];

export const MOCK_INJURIES: Injury[] = [
  {
    id: "i1",
    playerId: "8",
    type: "Hamstring Strain",
    startDate: new Date("2024-10-05"),
    expectedReturnDate: new Date("2024-11-15"),
    status: "active",
    notes: "Recovery progressing well, light training resumed",
  },
];

export const MOCK_TRAINING: TrainingSession[] = [
  {
    id: "t1",
    playerId: "1",
    date: new Date("2024-10-20"),
    type: "Tactical Training",
    performance: 8,
    notes: "Excellent positioning and decision making",
  },
  {
    id: "t2",
    playerId: "4",
    date: new Date("2024-10-20"),
    type: "Shooting Practice",
    performance: 9,
    notes: "Outstanding finishing accuracy",
  },
];

