import { Transfer } from "@/lib/types";

export const MOCK_TRANSFERS: Transfer[] = [
  {
    id: "tr1",
    playerId: "2",
    playerName: "James Rodriguez",
    fromTeam: "Real Madrid",
    toTeam: "Barcelona",
    transferDate: new Date("2024-07-15"),
    fee: 45000000,
    status: "completed",
    initiatedBy: "admin1",
    createdAt: new Date("2024-06-20"),
  },
  {
    id: "tr2",
    playerId: "6",
    playerName: "Carlos Mendes",
    fromTeam: "Benfica",
    toTeam: "Real Madrid",
    transferDate: new Date("2024-08-01"),
    fee: 35000000,
    status: "completed",
    initiatedBy: "scout1",
    createdAt: new Date("2024-07-10"),
  },
  {
    id: "tr3",
    playerId: "9",
    playerName: "Kevin De Bruyne Jr",
    fromTeam: "Manchester City",
    toTeam: "Chelsea",
    transferDate: new Date("2024-08-20"),
    fee: 55000000,
    status: "completed",
    initiatedBy: "admin1",
    createdAt: new Date("2024-08-01"),
  },
  {
    id: "tr4",
    playerId: "12",
    playerName: "Sergio Ramos Jr",
    fromTeam: "Paris Saint-Germain",
    toTeam: "Real Madrid",
    transferDate: new Date("2024-09-05"),
    fee: 28000000,
    status: "completed",
    initiatedBy: "scout2",
    createdAt: new Date("2024-08-15"),
  },
  {
    id: "tr5",
    playerId: "16",
    playerName: "Luka Modric II",
    fromTeam: "Inter Milan",
    toTeam: "Real Madrid",
    transferDate: new Date("2024-11-15"),
    fee: 40000000,
    status: "pending",
    initiatedBy: "admin1",
    createdAt: new Date("2024-10-01"),
  },
  {
    id: "tr6",
    playerId: "19",
    playerName: "Neymar Jr II",
    fromTeam: "Al-Hilal",
    toTeam: "Paris Saint-Germain",
    transferDate: new Date("2024-12-01"),
    fee: 60000000,
    status: "pending",
    initiatedBy: "scout1",
    createdAt: new Date("2024-10-10"),
  },
];

